import { test, expect } from "./helpers/test";
import { loginTestAudience } from "./helpers/auth";
import { FIXTURE_ORGANISER } from "./helpers/roles";
import { authFile } from "./helpers/personas";

/**
 * Regression test for PR #199 (26 Jul, session 35): the login "code"
 * identifier was case-sensitive - a correct AFA/ART/ORG/VEN code typed in
 * lowercase or mixed case failed with the same generic invalid-account
 * error as a genuinely wrong code, since resolveIdentifierToUser did an
 * exact-case pattern test and exact-case DB lookup while codes are always
 * generated uppercase by the DB's generate_role_code() function.
 *
 * Reuses the existing fixture Organiser (see helpers/roles.ts) rather than
 * seeding a new account.
 *
 * These two are also the suite's test of the login form itself: every
 * other spec reuses a session saved by global-setup.ts.
 *
 * 3 Oct 2026, two things were wrong here and hid each other:
 *   - The fixture's code was hardcoded ("AFA2607000053"). Codes are
 *     generated by the database, so the 10 Sep reseed gave the account a
 *     new one and the login has been answering "Invalid credentials" since.
 *     The code is now read from the account itself (its own /api/users/me,
 *     with the session global-setup saved) on every run.
 *   - The success check was a URL pattern that matched any address ending
 *     in a slash, /login/ included, so both tests passed anyway.
 *     loginTestAudience now ends on expectSignedIn (off the login page AND
 *     a real session), which a rejected code fails.
 */

let fixtureCode = "";

test.beforeAll(async ({ playwright, baseURL }) => {
  const api = await playwright.request.newContext({ baseURL, storageState: authFile("fixtureOrganiser") });
  try {
    const res = await api.get("/api/users/me/");
    const body = (await res.json()) as { user?: { code?: string | null } };
    fixtureCode = body.user?.code ?? "";
  } finally {
    await api.dispose();
  }
  // Uppercase letters + digits, or lower/mixed-casing it proves nothing.
  expect(fixtureCode, "the fixture Organiser's login code").toMatch(/^[A-Z]{3}\d+$/);
});

test("login accepts a valid code typed in lowercase", async ({ page }) => {
  await loginTestAudience(page, fixtureCode.toLowerCase(), FIXTURE_ORGANISER.password);
});

test("login accepts a valid code typed in mixed case", async ({ page }) => {
  // Flip every other character's case - "Afa2607000053" would only catch an
  // accidental case-insensitive-at-the-prefix-only fix, mix it up properly.
  const mixed = fixtureCode
    .split("")
    .map((ch, i) => (i % 2 === 0 ? ch.toLowerCase() : ch.toUpperCase()))
    .join("");

  await loginTestAudience(page, mixed, FIXTURE_ORGANISER.password);
});
